TRANSLATIONS = {
    'pt': {
        # Application titles
        'app_title': 'Análise de Dados Físicos',
        'curve_fitting_title': 'Ajuste de Curvas',
        
        # Common strings
        'error': 'Erro',
        'file_not_found': "O arquivo '{file}' não foi encontrado.",
        'invalid_number': "Por favor, insira um número válido.",
        'browse': 'Procurar',
        'equation': 'Equação:',
        'progress': 'Progresso',
        'results': 'Resultados',
        'perform_fit': 'Realizar Ajuste',
        'save_graph': 'Salvar Gráfico',

        # Menu items
        'file': 'Arquivo',
        'open': 'Abrir',
        'save': 'Salvar',
        'exit': 'Sair',
        'language': 'Idioma',
        'help': 'Ajuda',
        'about': 'Sobre',

        # Curve Fitting specific
        'data_input': 'Entrada de Dados',
        'load_data': 'Carregar Dados',
        'fit_model': 'Ajustar Modelo',
        'plot_data': 'Plotar Dados',
        'parameters': 'Parâmetros',
        'chi_squared': 'Chi Quadrado',
        'r_squared': 'R Quadrado',
        'initial_values': 'Valores Iniciais',
        'fit_results': 'Resultados do Ajuste',
        'data_file': 'Arquivo de Dados:',
        'max_iterations': 'Máx. iterações:',
        'fit_points': 'Pontos do ajuste:',
        'graph_settings': 'Configurações do Gráfico',
        'graph_title': 'Título:',
        'x_scale': 'Escala X:',
        'y_scale': 'Escala Y:',
        'initial_estimates': 'Estimativas Iniciais',

        # File dialogs
        'open_file': 'Abrir Arquivo',
        'save_file': 'Salvar Arquivo',
        'supported_files': 'Arquivos Suportados',
        'all_files': 'Todos os Arquivos',

        # Error messages
        'invalid_file': 'Arquivo inválido',
        'invalid_data': 'Dados inválidos',
        'fit_error': 'Erro no ajuste',
        'plot_error': 'Erro ao plotar',
        'invalid_formula': 'Erro ao processar a fórmula: {error}',

        # Plot labels
        'x_axis': 'Eixo X',
        'y_axis': 'Eixo Y',
        'data_points': 'Pontos',
        'fit_curve': 'Ajuste',
        'residuals': 'Resíduos',

        # Additional translations
        'verify_and_retry': 'Ocorreu um erro. Verifique os dados e tente novamente.',
        'select_data_file': 'Selecionar arquivo de dados',
        'fit_in_progress': 'Ajuste em andamento...',
        'fit_complete': 'Ajuste concluído!',
        'fit_error': 'Erro durante o ajuste',
        'starting_fit': 'Iniciando ajuste...',
        'iteration': 'Iteração: {iter}',
        'reduced_chi_squared': 'Chi² reduzido',
        'equation': 'Equação: y = ',
        'fitting_parameters': 'Parâmetros do Ajuste',
        'num_points': 'Pontos do ajuste:',
        'positive_points': 'O número de pontos deve ser positivo',
        'invalid_points': 'Por favor, insira um número válido de pontos para o ajuste.',
        'language_label': 'Idioma',
        'curve_fitting': 'Ajuste de Curvas',
        'uncertainty_calc': 'Cálculo de Incertezas',
        'title': 'Título:',
        # Uncertainty calculation (calculo_incertezas_gui.py)
        'operation_mode': 'Modo de operação',
        'calc_value_uncertainty': 'Calcular valor e incerteza',
        'generate_uncertainty_formula': 'Gerar fórmula de incerteza',
        'number_of_variables': 'Número de variáveis:',
        'create_fields': 'Criar campos',
        'variables_list': 'Lista de variáveis (separadas por vírgula):',
        'calculate': 'Calcular',
        'generate_formula': 'Gerar fórmula',
        'copy_formula': 'Copiar fórmula',
        'show_latex': 'Exibir em LaTeX',
        'invalid_vars': 'Por favor, insira nomes e valores válidos para as variáveis.',
        'variable': 'Variável',
        'value': 'Valor',
        'uncertainty': 'Incerteza',
        'formula': 'Fórmula:',
        'linear': 'Linear',
        'log': 'Log',
        'axis_labels': 'Rótulos dos Eixos',
        'x_label': 'Rótulo X',
        'y_label': 'Rótulo Y',
    },
    'en': {
        # Application titles
        'app_title': 'Physics Data Analysis',
        'curve_fitting_title': 'Curve Fitting',
        
        # Common strings
        'error': 'Error',
        'file_not_found': "The file '{file}' was not found.",
        'invalid_number': "Please enter a valid number.",
        'browse': 'Browse',
        'equation': 'Equation:',
        'progress': 'Progress',
        'results': 'Results',
        'perform_fit': 'Perform Fit',
        'save_graph': 'Save Graph',

        # Menu items
        'file': 'File',
        'open': 'Open',
        'save': 'Save',
        'exit': 'Exit',
        'language': 'Language',
        'help': 'Help',
        'about': 'About',

        # Curve Fitting specific
        'data_input': 'Data Input',
        'load_data': 'Load Data',
        'fit_model': 'Fit Model',
        'plot_data': 'Plot Data',
        'parameters': 'Parameters',
        'chi_squared': 'Chi Squared',
        'r_squared': 'R Squared',
        'initial_values': 'Initial Values',
        'fit_results': 'Fit Results',
        'data_file': 'Data File:',
        'max_iterations': 'Max iterations:',
        'fit_points': 'Fit points:',
        'graph_settings': 'Graph Settings',
        'graph_title': 'Title:',
        'x_scale': 'X Scale:',
        'y_scale': 'Y Scale:',
        'initial_estimates': 'Initial Estimates',

        # File dialogs
        'open_file': 'Open File',
        'save_file': 'Save File',
        'supported_files': 'Supported Files',
        'all_files': 'All Files',

        # Error messages
        'invalid_file': 'Invalid file',
        'invalid_data': 'Invalid data',
        'fit_error': 'Fit error',
        'plot_error': 'Plot error',
        'invalid_formula': 'Error processing formula: {error}',

        # Plot labels
        'x_axis': 'X Axis',
        'y_axis': 'Y Axis',
        'data_points': 'Data Points',
        'fit_curve': 'Fit',
        'residuals': 'Residuals',

        # Additional translations
        'verify_and_retry': 'An error occurred. Please verify the data and try again.',
        'select_data_file': 'Select data file',
        'fit_in_progress': 'Fit in progress...',
        'fit_complete': 'Fit complete!',
        'fit_error': 'Error during fit',
        'starting_fit': 'Starting fit...',
        'iteration': 'Iteration: {iter}',
        'reduced_chi_squared': 'Reduced Chi²',
        'equation': 'Equation: y = ',
        'fitting_parameters': 'Fitting Parameters',
        'num_points': 'Fit points:',
        'positive_points': 'Number of points must be positive',
        'invalid_points': 'Please enter a valid number of points for the fit.',
        'language_label': 'Language',
        'curve_fitting': 'Curve Fitting',
        'uncertainty_calc': 'Uncertainty Calculation',
        'title': 'Title:',
        # Uncertainty calculation (calculo_incertezas_gui.py)
        'operation_mode': 'Operation mode',
        'calc_value_uncertainty': 'Calculate value and uncertainty',
        'generate_uncertainty_formula': 'Generate uncertainty formula',
        'number_of_variables': 'Number of variables:',
        'create_fields': 'Create fields',
        'variables_list': 'Variables list (comma separated):',
        'calculate': 'Calculate',
        'generate_formula': 'Generate formula',
        'copy_formula': 'Copy formula',
        'show_latex': 'Show LaTeX',
        'invalid_vars': 'Please enter valid names and values for the variables.',
        'variable': 'Variable',
        'value': 'Value',
        'uncertainty': 'Uncertainty',
        'formula': 'Formula:',
        'linear': 'Linear',
        'log': 'Log',
        'axis_labels': 'Axis Labels',
        'x_label': 'X Label',
        'y_label': 'Y Label',
    }
}